[default]
database_url = "sqlite:///Users/sunday00/workspace/web-skill-labs/rust/packt-rocket-1/ch09-1-post/rocket_exam.db"
log_level = "normal"
template_dir = "src/views"

[debug]
database_url = "sqlite:///Users/sunday00/workspace/web-skill-labs/rust/packt-rocket-1/ch09-1-post/rocket_exam.db"
