[default]
database_url = "sqlite:///Users/sunday00/workspace/web-skill-labs/rust/packt-rocket-1/ch04-2-db/rocket_exam.db"

[debug]
database_url = "sqlite:///Users/sunday00/workspace/web-skill-labs/rust/packt-rocket-1/ch04-2-db/rocket_exam.db"