services:
  kafka:
    container_name: kafka
    image: apache/kafka:3.7.0
    ports:
      - "9092:9092"
    volumes:
      - ./data:/var/lib/kafka/data
      - ./config/server.properties:/etc/kafka/docker/server.properties
      - ./config/log4j.properties:/etc/kafka/docker/log4j.properties
      - ./config/tools-log4j.properties:/etc/kafka/docker/tools-log4j.properties

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: peters_kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9091