// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file hello.proto (package hello, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { SendHelloRequest, SendHelloResponse } from "./hello_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service hello.Hello
 */
export const Hello = {
  typeName: "hello.Hello",
  methods: {
    /**
     * @generated from rpc hello.Hello.SendHello
     */
    sendHello: {
      name: "SendHello",
      I: SendHelloRequest,
      O: SendHelloResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

