services:
  mongo_repl:
    image: ubuntu:24.04
    container_name: mongo_repl
    ports:
      - 27217:27217
      - 27218:27218
      - 27219:27219
    tty: true
    volumes:
      - ./conf:/etc/mongo/confs
      - ./data:/data/db