services:
  mongo1:
    image: mongo:latest
    container_name: mongo1
    command: ["mongod","--config", "/etc/mongod.conf"]
    ports:
      - 27217:27017
    volumes:
      - ./conf/mongod.conf:/etc/mongod.conf
      - ./data/data1:/data/db
    healthcheck:
      test: echo "db.runCommand('ping').ok" | mongosh localhost:27017/test --quiet
      interval: 10s
      retries: 5

  mongo2:
    image: mongo:latest
    container_name: mongo2
    command: ["mongod", "--config", "/etc/mongod.conf"]
    ports:
      - 27218:27017
    volumes:
      - ./conf/mongod.conf:/etc/mongod.conf
      - ./data/data2:/data/db

  mongo3:
    image: mongo:latest
    container_name: mongo3
    command: ["mongod", "--config", "/etc/mongod.conf"]
    ports:
      - 27219:27017
    volumes:
      - ./conf/mongod.conf:/etc/mongod.conf
      - ./data/data3:/data/db