[package]
name = "our_package"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
rand = "0.8.5"
rsa = "0.9.7"

[[bin]]
name = "our_package"
path = "src/main.rs"

[lib]
name = "our_package"
path = "src/lib.rs"
