# /etc/nginx/http.d/default.conf
# This is a default site configuration which will simply return 404, preventing
# chance access to any other virtualhost.

server {
        listen 80 default_server;
        listen [::]:80 default_server;

        location / {
                root /var/www/dist;
                index index.html;
                try_files $uri /index.html;
        }
}

## reload nginx -s reload
## shut nginx -g 'daemon off;'