### getter
POST http://127.0.0.1:4444/rpc
Content-Type: application/json

{
  "action": "getTodos",
  "payload": {}
}

### setter
POST http://127.0.0.1:4444/rpc
Content-Type: application/json

{
  "action": "createTodo",
  "payload": {"message":  "work hard"}
}